# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test Showcase

on:
  push:
    paths:
      - "app/client-next-ts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: app/client-next-ts/yarn.lock
      - name: Install modules
        run: yarn install --frozen-lockfile
        working-directory: ./app/client-next-ts
      - name: Build
        run: yarn build
        working-directory: ./app/client-next-ts
      - name: Run tests
        run: yarn test
        working-directory: ./app/client-next-ts
